#!/bin/bash
#-------------------------------------------------------------------------------
#Created by helmuthdu mailto: helmuthdu[at]gmail[dot]com
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

#MAINMENU {{{
  # 1) Basic Setup
  # 2) Desktop Environment
  # 3) Accessories Apps
  # 4) Development Apps
  # 5) Office Apps
  # 6) System Apps
  # 7) Graphics Apps
  # 8) Internet Apps
  # 9) Audio Apps
  #10) Video Apps
  #11) Games
  #12) LAMP
  #13) Fonts
  #14) Extra
  #15) Clean Orphan Packages
  MAINMENU="1-13 15"
#}}}
#BASIC SETUP {{{
  CUPS="y"
  CUSTOMREPO="n"         # Add custom repositories
  FIRMWARE="y"           # Install custom firmwares
  GITTOR="y"
  NFS="n"
  READAHEAD="y"
  SAMBA="y"
  SSH="y"
  TLP="n"                # Laptop Power Manager
  ZRAM="y"
  PROPRIETARY_DRIVER="n" # Proprietary (NVIDIA|ATI) driver
  #FONT CONFIGURATION {{{
    # 1) Default
    # 2) Infinality
    # 3) Ubuntu
    FONTCONFIG=2
  #}}}
  #ADDITIONAL FIRMWARE {{{
    # 1) aic94xx-firmware
    # 2) alsa-firmware
    # 3) b43
    # 4) b43legacy
    # 5) bfa-firmware
    # 6) bluez-firmware
    # 7) broadcom-wl
    # 8) ipw2100
    # 9) ipw2200
    #10) libffado [Firmware Audio Devices]
    #11) libmtp [Android Devices]
    #12) libraw1394 [IEE1394 Driver]
    FIRMWARE_OPTIONS="11"
  #}}}
#}}}
#DESKTOP ENVIRONMENT|WINDOW MANAGER {{{
  # 1) Cinnamon
  # 2) E17
  # 3) GNOME
  # 4) KDE
  # 5) LXDE
  # 6) Mate
  # 7) XFCE
  # 8) Awesome
  # 9) Fluxbox
  #10) OpenBox
  DESKTOPENV=3
  #KDE {{{
    # 1) Full
    # 2) Minimal
    KDE_INSTALL="1"
    # 1) Apper
    # 2) Choqok
    # 3) Digikam
    # 4) K3b
    # 5) Rosa Icon
    # 6) Caledonia Bundle
    # 7) Skrooge
    # 8) Yakuake
    KDE_OPTIONS="1-8"
  #}}}
  #ESSENTIAL APPS [E17,LXDE,Awesome,Fluxbox,OpenBox] {{{
    # 1) Display Manager
    # 2) Dmenu
    # 3) Viewnior
    # 4) Gmrun
    # 5) PCManFM
    # 6) rxvt-unicode
    # 7) Scrot
    # 8) Thunar
    # 9) Tint2
    #10) Volwheel
    #11) Xfburn
    #12) Xcompmgr
    #13) Zathura
    MISCAPPS="1 3"
  #}}}
  #DISPLAY MANAGER {{{
    # 1) Elsa
    # 2) GDM
    # 3) LightDM
    # 4) LXDM
    # 5) Slim
    DISPLAY_MANAGER="3"
  #}}}
  # 1) Icons Themes
  # 2) GTK2|GTK3 Themes
  THEMES_OPTIONS="1 2"
  #ICONS THEMES {{{
    # 1) Faenza
    # 2) Faience
    # 3) Moka
    # 4) Nitrux
    # 5) Numix
    ICONS_THEMES="1-5"
  #}}}
  #GTK THEMES {{{
    # 1) Greybird
    # 2) Numix
    # 3) Orion
    # 4) Zukitwo
    GTK_THEMES="1-4"
  #}}}
#}}}
#NETWORK MANAGER {{{
  # 1) NetworkManager
  # 2) Wicd
  # 3) ConnMan
  # n) None
  NETWORKMANAGER=1
  #USB 3G MODEM SUPPORT
  USBMODEM="y"
#}}}
#ACCESSORIES {{{
  # 1) Cairo Dock
  # 2) Catfish
  # 3) Conky
  # 4) Docky
  # 5) Galculator
  # 6) Kupfer
  # 7) Pamac
  # 8) Pyrenamer
  # 9) Shutter
  #10) Springseed
  #11) Stormcloud
  #12) Synapse
  #13) Terminator
  #14) Zim
  ACCESSORIES_OPTIONS=""
#}}}
#DEVELOPEMENT {{{
  # 1) Aptana Studio
  # 2) Bluefish
  # 3) Eclipse
  # 4) Emacs
  # 5) Gvim
  # 6) Geany
  # 7) IntelliJ IDEA
  # 8) Kdevelop
  # 9) Monodevelop
  #10) Netbeans
  #11) NodeJS
  #12) Ruby on Rails
  #13) OpenJDK
  #14) Oracle JDK
  #15) QT Creator
  #16) Sublime Text
  #17) Debuggers
  #18) MySQL Workbench
  #19) Navicat
  #20) Meld
  DEVELOPMENT_OPTIONS="11 14 20"
  #ECLIPSE {{{
    # 1) Eclipse Classic
    # 2) Eclipse IDE for C/C++ Developers
    # 3) Android Development Tools for Eclipse
    # 4) Web Development Tools for Eclipse
    # 5) PHP Development Tools for Eclipse
    # 6) Python Development Tools for Eclipse
    # 7) Aptana Studio plugin for Eclipse
    # 8) Vim-like editing plugin for Eclipse
    # 9) Git support plugin for Eclipse
    #10) Colortheme for Eclipse
    ECLIPSE_OPTIONS="1"
  #}}}
  #NODEJS {{{
    # 1) backbone
    # 2) bower
    # 3) coffee-script
    # 4) express
    # 5) grunt
    # 6) jshint
    # 7) jslint
    # 8) less
    # 9) markdown
    # 10) mocha
    # 11) stylus
    # 12) uglify-js
    # 13) underscore
    # 14) yeoman
    NODEJS_OPTIONS="2 6 7 8 12 14"
  #}}}
#}}}
#OFFICE {{{
  # 1) LibreOffice
  # 2) Abiword+Gnumeric|Calligra
  # 3) Latex + Texmaker
  # 4) Calibre
  # 5) GCStar
  # 6) Geeknote
  # 7) Homebank
  # 8) Impressive
  # 9) Nitrotask
  #10) OCRFeeder
  #11) UberWriter
  #12) Xmind
  OFFICE_OPTIONS="1"
#}}}
#SYSTEM TOOLS {{{
  # 1) ClamAV
  # 2) FirewallD
  # 3) UFW
  # 4) Gparted
  # 5) Grsync
  # 6) Htop
  # 7) Virtualbox
  # 8) Webmin
  # 9) Wine
  SYSTEMTOOLS_OPTIONS="7 9"
#}}}
#GRAPHICS {{{
  # 1) Blender
  # 2) Gimp
  # 3) Gthumb
  # 4) Inkscape
  # 5) MComix
  # 6) Mypaint
  # 7) Pencil
  # 8) Scribus
  # 9) Shotwell
  #10) Simple Scan
  #11) XnViewMP
  GRAPHICS_OPTIONS="2-7 9"
#}}}
#INTERNET {{{
  # 1) Browser
  # 2) Download|Fileshare
  # 3) Email|RSS
  # 4) Instant Messaging|IRC
  # 5) Mapping Tools
  # 6) VNC|Desktop Share
  INTERNET_OPTIONS="1-6"
  #BROWSER {{{
    # 1) Chromium
    # 2) Google Chrome
    # 3) Midori|Rekonq
    # 4) Mozilla Firefox
    # 5) Opera
    BROWSERS_OPTIONS="2 4"
  #}}}
  #DOWNLOAD|FILESHARE {{{
    # 1) AeroFS
    # 2) BitTorrent Sync
    # 3) Deluge
    # 4) Dropbox
    # 5) FlareGet
    # 6) Jdownloader
    # 7) qBittorrent
    # 8) Sparkleshare
    # 9) Spider Oak
    #10) Trasmission
    #11) uGet
    DOWNLOAD_OPTIONS="4 10"
  #}}}
  #EMAIL|RSS {{{
    # 1) Mozilla Thunderbird
    # 2) Liferea
    EMAIL_OPTIONS=""
  #}}}
  #IM|IRC {{{
    # 1) Emesene
    # 2) Google Talk-Plugin
    # 3) Pidgin
    # 4) Skype
    # 5) Teamspeak
    # 6) Irssi
    # 7) HexChat|Konversation
    IM_OPTIONS="4"
  #}}}
  #MAPPING {{{
    # 1) Google Earth
    # 2) NASA World Wind
    MAPPING_OPTIONS="1"
  #}}}
  #VNC|Desktop Share {{{
    # 1) Remmina
    # 2) Teamviewer
    VNC_OPTIONS=""
  #}}}
#}}}
#AUDIO {{{
  # 1) Players
  # 2) Editors|Tools
  # 3) Codecs
  AUDIO_OPTIONS="1-3"
  #PLAYERS {{{
    # 1) Amarok
    # 2) Audacious
    # 3) Banshee
    # 4) Clementine
    # 5) Deadbeef
    # 6) Guayadeque
    # 7) Musique
    # 8) Nuvola
    # 9) Rhythmbox
    #10) Radiotray
    #11) Spotify
    #12) Tomahawk
    #13) Timidity++
    #14) Xnoise
    AUDIO_PLAYER_OPTIONS="4"
  #}}}
  #EDITORS|TOOLS {{{
    # 1) Soundconverter|Soundkonverter
    # 2) Easytag
    # 3) Audacity
    # 4) OcenAudio
    AUDIO_EDITOR_OPTIONS="1 2"
  #}}}
#}}}
#VIDEO {{{
  # 1) Players
  # 2) Editors|Tools
  # 3) Codecs
  VIDEO_OPTIONS="1-3"
  #PLAYERS {{{
    # 1) Audience
    # 2) Gnome Mplayer
    # 3) Parole
    # 4) Minitube
    # 5) Miro
    # 6) Rosa Media Player
    # 7) SMplayer
    # 8) VLC
    # 9) XBMC
    #10) mpv
    VIDEO_PLAYER_OPTIONS="8 9"
  #}}}
  #EDITORS|TOOLS {{{
    # 1) Avidemux
    # 2) Arista
    # 3) Handbrake
    # 4) Transmageddon
    # 5) Kdenlive
    # 6) Openshot
    # 7) Pitivi
    # 8) Kazam
    VIDEO_EDITOR_OPTIONS="2"
  #}}}
#}}}
#GAMES {{{
  # 1) Action|Adventure
  # 2) Arcade|Platformer
  # 3) Dungeon
  # 4) Emulators
  # 5) FPS
  # 6) MMO
  # 7) Puzzle
  # 8) RPG
  # 9) Racing
  #10) Simulation
  #11) Strategy
  #12) PlayOnLinux
  #13) Steam
  GAMES_OPTIONS=""
  #ACTION {{{
    # 1) Astromenace
    # 2) Counter-Strike 2D
    # 3) Dead Cyborg
    # 4) M.A.R.S.
    # 5) Nikki
    # 6) OpenTyrian
    # 7) Sonic Robot Bast 2
    # 8) SteelStorm
    ACTION=""
  #}}}
  #ARCADE {{{
    # 1) Abuse
    # 2) Battle Tanks
    # 3) Bomberclone
    # 4) Those Funny Funguloids
    # 5) Frogatto
    # 6) Goonies
    # 7) Mari0
    # 8) Neverball
    # 9) Opensonic
    #10) Robombs
    #11) Super Mario Chronicles
    #12) X-Moto
    ARCADE=""
  #}}}
  #DUNGEON {{{
    # 1) Adom
    # 2) Tales of MajEyal
    # 3) Lost Labyrinth
    # 4) S.C.O.U.R.G.E.
    # 5) Stone-Soupe
    DUNGEON=""
  #}}}
  #EMULATORS {{{
    # 1) BSNES
    # 2) Desmume
    # 3) Dolphin
    # 4) ePSXe
    # 5) Project64
    # 6) Snes9x
    # 7) VisualBoyAdvanced
    # 8) wxMupen64Plus
    # 9) ZSNES
    EMULATORS=""
  #}}}
  #FPS {{{
    # 1) AlienArena
    # 2) Warsow
    # 3) Wolfenstein: Enemy Territory
    # 4) World of Padman
    # 5) Xonotic
    FPS=""
  #}}}
  #MMO {{{
    # 1) Heroes of Newerth
    # 2) League of Legends
    # 3) ManaPlus
    # 4) Runescape
    # 5) Savage II
    # 6) Spiral Knights
    # 7) Wakfu
    MMO=""
  #}}}
  #PUZZLE {{{
    # 1) Frozen Bubble
    # 2) Puzzle Moppet
    # 3) Numptyphysics
    PUZZLE=""
  #}}}
  #RPG {{{
    # 1) Ardentryst
    # 2) Flare
    # 3) Freedroid RPG
    RPG=""
  #}}}
  #RACING {{{
    # 1) Maniadrive
    # 2) Death Rally
    # 3) Stuntrally
    # 4) SupertuxKart
    # 5) Speed Dreams
    RACING=""
  #}}}
  #SIMULATION {{{
    # 1) Simultrans
    # 2) Theme Hospital
    # 3) OpenTTD
    SIMULATION=""
  #}}}
  #STRATEGY {{{
    # 1) 0ad
    # 2) Hedgewars
    # 3) MegaGlest
    # 4) Warzone 2100
    # 5) Wesnoth
    # 6) Zod
    STRATEGY=""
  #}}}
#}}}
#WEBSERVER {{{
  # 1) LAMP - APACHE, MariaDB & PHP
  # 2) LAPP - APACHE, POSTGRESQL & PHP
  # 3) LEMP - NGINX, MariaDB & PHP
  # 4) LEPP - NGINX, POSTGRESQL & PHP
  WEBSERVER=4
  POSTGIS="n"
#}}}
#FONTS {{{
  # 1) ttf-dejavu
  # 2) ttf-funfonts
  # 3) ttf-google-webfonts
  # 4) ttf-liberation
  # 5) ttf-ms-fonts
  # 6) ttf-vista-fonts
  # 7) wqy-microhei
  FONTS_OPTIONS="1-7"
#}}}
#EXTRA {{{
  # 1) Global Menu
  EXTRA_OPTIONS=""
#}}}
