#!/bin/bash
#-------------------------------------------------------------------------------
#Created by helmuthdu mailto: helmuthdu[at]gmail[dot]com
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

#MAINMENU {{{
  # 1) Basic Setup
  # 2) Desktop Environment
  # 3) Accessories Apps
  # 4) Development Apps
  # 5) Office Apps
  # 6) System Apps
  # 7) Graphics Apps
  # 8) Internet Apps
  # 9) Audio Apps
  #10) Video Apps
  #11) Games
  #12) LAMP
  #13) Fonts
  #14) Extra
  #15) Clean Orphan Packages
  MAINMENU="1-13 15"
#}}}
#BASIC SETUP {{{
  CUPS="y"
  CUSTOMREPO="n"         # Add custom repositories
  FIRMWARE="n"           # Install custom firmwares
  GITTOR="y"
  NFS="n"
  PRELOAD="y"
  SAMBA="y"
  SSH="y"
  TLP="n"                # Laptop Power Manager
  ZRAM="y"
  PROPRIETARY_DRIVER="n" # Proprietary (NVIDIA|ATI) driver
  #FONT CONFIGURATION {{{
    # 1) Default
    # 2) Infinality
    # 3) Ubuntu
    FONTCONFIG=1
  #}}}
  #ADDITIONAL FIRMWARE {{{
    # 1) alsa-firmware
    # 2) ipw2100
    # 3) ipw2200
    # 4) b43
    # 5) b43legacy
    # 6) broadcom-wl
    # 7) zd1211-firmware
    # 8) bluez-firmware
    # 9) libffado [Fireware Audio Devices]
    #10) libraw1394 [IEE1394 Driver]
    #11) aic94xx-firmware
    #12) bfa-firmware
    FIRMWARE_OPTIONS="1"
  #}}}
#}}}
#DESKTOP ENVIRONMENT|WINDOW MANAGER {{{
  # 1) Cinnamon
  # 2) E17
  # 3) GNOME
  # 4) KDE
  # 5) LXDE
  # 6) Mate
  # 7) XFCE
  # 8) Awesome
  # 9) Fluxbox
  #10) OpenBox
  DESKTOPENV=3
  #KDE {{{
    # 1) Apper
    # 2) Choqok
    # 3) Digikam
    # 4) K3b
    # 5) Rosa Icon
    # 6) Plasma Themes [Caledonia, Produkt, Ronak]
    # 7) Yakuake
    KDE_OPTIONS="1-7"
  #}}}
  #ESSENTIAL APPS [E17,LXDE,Awesome,Fluxbox,OpenBox] {{{
    # 1) Display Manager
    # 2) Dmenu
    # 3) Viewnior
    # 4) Gmrun
    # 5) PCManFM
    # 6) rxvt-unicode
    # 7) Scrot
    # 8) Thunar
    # 9) Tint2
    #10) Volwheel
    #11) Xfburn
    #12) Xcompmgr
    #13) Zathura
    MISCAPPS="1 3"
  #}}}
  #DISPLAY MANAGER {{{
    # 1) Elsa
    # 2) GDM
    # 3) LightDM
    # 4) LXDM
    # 5) Slim
    DISPLAY_MANAGER="3"
  #}}}
  # 1) Icons Themes
  # 2) GTK2|GTK3 Themes
  # 3) GNOME|CINNAMON Themes
  THEMES_OPTIONS="1 2"
  #ICONS THEMES {{{
    # 1) Awoken
    # 2) Elementary XFCE
    # 3) Faenza
    # 4) Faenza-Cupertino
    # 5) Faience
    # 6) iNX
    # 7) Matrilineare
    # 8) Nitrux
    ICONS_THEMES="3 5"
  #}}}
  #GTK THEMES {{{
    # 1) Greybird
    # 2) Faience
    # 3) Gnome Cupertino
    # 4) MediterraneanNight
    # 5) Numix
    # 6) Zukitwo
    GTK_THEMES="1-6"
  #}}}
  #GNOME SHELL THEMES {{{
    # 1) Default-Mod
    GNOME_SHELL_THEMES="1"
  #}}}
  #CINNAMON THEMES {{{
    # 1) Ambience
    # 2) Baldr
    # 3) Eleganse
    # 4) Elementary-luna
    # 5) Faience
    # 6) Gnome
    # 7) Google+
    # 8) Helios
    # 9) Holo
    #10) Nadia
    #11) Loki
    CINNAMON_THEMES="5"
  #}}}
#}}}
#NETWORK MANAGER {{{
  # 1) NetworkManager
  # 2) Wicd
  # 3) ConnMan
  # n) None
  NETWORKMANAGER=1
  #USB 3G MODEM SUPPORT
  USBMODEM="y"
#}}}
#ACCESSORIES {{{
  # 1) Cairo Dock
  # 2) Catfish
  # 3) Conky
  # 4) Dockbarx
  # 5) Docky
  # 6) Galculator|Speedcrunch
  # 7) Terra [Drop-down Terminal]
  # 8) Kupfer
  # 9) Pyrenamer
  #10) Shutter
  #11) Stormcloud
  #12) Terminator
  #13) Zim
  ACCESSORIES_OPTIONS=""
#}}}
#DEVELOPEMENT {{{
  # 1) Aptana Studio
  # 2) Bluefish
  # 3) Eclipse
  # 4) Emacs
  # 5) Gvim
  # 6) Geany
  # 7) IntelliJ IDEA
  # 8) Kdevelop
  # 9) Netbeans
  #10) OpenJDK
  #11) Oracle JDK
  #12) QT Creator
  #13) Sublime Text 2
  #14) Debugger & Syntax Tools
  #15) MySQL Workbench
  #16) SQL Power Architect
  #17) Meld
  #18) RabbitVCS
  DEVELOPMENT_OPTIONS="11 5 14"
  #ECLIPSE {{{
    # 1) Eclipse Classic
    # 2) Eclipse IDE for C/C++ Developers
    # 3) Android Development Tools for Eclipse
    # 4) Web Development Tools for Eclipse
    # 5) PHP Development Tools for Eclipse
    # 6) Python Development Tools for Eclipse
    # 7) Aptana Studio plugin for Eclipse
    # 8) Vim-like editing plugin for Eclipse
    # 9) Git support plugin for Eclipse
    #10) Colortheme for Eclipse
    ECLIPSE_OPTIONS="1"
  #}}}
#}}}
#OFFICE {{{
  # 1) LibreOffice
  # 2) Abiword+Gnumeric|Calligra
  # 3) Latex + Texmaker
  # 4) Calibre
  # 5) GCStar
  # 6) Homebank
  # 7) Impressive
  # 8) Nitrotask
  # 9) OCRFeeder
  #10) UberWriter
  #11) Xmind
  OFFICE_OPTIONS="1 10"
#}}}
#SYSTEM TOOLS {{{
  # 1) ClamAV
  # 2) FirewallD
  # 3) Gparted
  # 4) Grsync
  # 5) Htop
  # 6) Virtualbox
  # 7) Webmin
  # 8) Wine
  SYSTEMTOOLS_OPTIONS="3-6 8"
#}}}
#GRAPHICS {{{
  # 1) Blender
  # 2) Gimp
  # 3) Gradiator
  # 4) Gthumb
  # 5) Inkscape
  # 6) MComix
  # 7) Mypaint
  # 8) Pencil
  # 9) Scribus
  #10) Shotwell
  #11) Simple Scan
  #12) XnViewMP
  GRAPHICS_OPTIONS="2-8 10"
#}}}
#INTERNET {{{
  # 1) Browser
  # 2) Download|Fileshare
  # 3) Email|RSS
  # 4) Instant Messaging
  # 5) IRC
  # 6) Mapping Tools
  # 7) VNC|Desktop Share
  INTERNET_OPTIONS="1-7"
  #BROWSER {{{
    # 1) Chromium
    # 2) Google Chrome
    # 3) Midori|Rekonq
    # 4) Mozilla Firefox
    # 5) Opera
    BROWSERS_OPTIONS="2 4"
  #}}}
  #DOWNLOAD|FILESHARE {{{
    # 1) Deluge
    # 2) Dropbox
    # 3) Jdownloader
    # 4) Nitroshare
    # 5) Sparkleshare
    # 6) Spider Oak
    # 7) Steadyflow
    # 8) Trasmission
    DOWNLOAD_OPTIONS="2 3"
  #}}}
  #EMAIL|RSS {{{
    # 1) Mozilla Thunderbird
    # 2) Liferea
    EMAIL_OPTIONS=""
  #}}}
  #IM {{{
    # 1) Emesene
    # 2) Google Talk-Plugin
    # 3) Pidgin
    # 4) Skype
    # 5) Teamspeak
    IM_OPTIONS="4"
  #}}}
  #IRC {{{
    # 1) Irssi
    # 2) X-Chat|Quassel
    IRC_OPTIONS=""
  #}}}
  #MAPPING {{{
    # 1) Google Earth
    # 2) NASA World Wind
    MAPPING_OPTIONS="1"
  #}}}
  #VNC|Desktop Share {{{
    # 1) Remmina
    # 2) Teamviewer
    VNC_OPTIONS=""
  #}}}
#}}}
#AUDIO {{{
  # 1) Players
  # 2) Editors|Tools
  # 3) Codecs
  AUDIO_OPTIONS="1-3"
  #PLAYERS {{{
    # 1) Amarok
    # 2) Audacious
    # 3) Banshee
    # 4) Clementine
    # 5) Deadbeef
    # 6) Exaile
    # 7) Musique
    # 8) Nuvola
    # 9) Rhythmbox
    #10) Radiotray
    #11) Spotify
    #12) Tomahawk
    #13) Timidity++
    #14) Xnoise
    AUDIO_PLAYER_OPTIONS="9"
  #}}}
  #EDITORS|TOOLS {{{
    # 1) Soundconverter|Soundkonverter
    # 2) Easytag
    # 3) Audacity
    # 4) OcenAudio
    AUDIO_EDITOR_OPTIONS="1"
  #}}}
#}}}
#VIDEO {{{
  # 1) Players
  # 2) Editors|Tools
  # 3) Codecs
  VIDEO_OPTIONS="1-3"
  #PLAYERS {{{
    # 1) Audience
    # 2) Gnome Mplayer
    # 3) Parole
    # 4) Minitube
    # 5) Miro
    # 6) Rosa Media Player
    # 7) SMplayer
    # 8) VLC
    # 9) XBMC
    VIDEO_PLAYER_OPTIONS="8 9"
  #}}}
  #EDITORS|TOOLS {{{
    # 1) Avidemux
    # 2) Arista
    # 3) Handbrake
    # 4) Transmageddon
    # 5) Kdenlive
    # 6) Openshot
    # 7) Pitivi
    # 8) Kazam
    VIDEO_EDITOR_OPTIONS="2"
  #}}}
#}}}
#GAMES {{{
  # 1) Action|Adventure
  # 2) Arcade|Platformer
  # 3) Dungeon
  # 4) Emulators
  # 5) FPS
  # 6) MMO
  # 7) Puzzle
  # 8) RPG
  # 9) Racing
  #10) Simulation
  #11) Strategy
  #12) PlayOnLinux
  #13) Steam
  GAMES_OPTIONS=""
  #ACTION {{{
    # 1) Astromenace
    # 2) Counter-Strike 2D
    # 3) Dead Cyborg
    # 4) M.A.R.S.
    # 5) Nikki
    # 6) OpenTyrian
    # 7) Sonic Robot Bast 2
    # 8) SteelStorm
    ACTION=""
  #}}}
  #ARCADE {{{
    # 1) Abuse
    # 2) Battle Tanks
    # 3) Bomberclone
    # 4) Those Funny Funguloids
    # 5) Frogatto
    # 6) Goonies
    # 7) Mari0
    # 8) Neverball
    # 9) Opensonic
    #10) Robombs
    #11) Super Mario Chronicles
    #12) X-Moto
    ARCADE=""
  #}}}
  #DUNGEON {{{
    # 1) Adom
    # 2) Tales of MajEyal
    # 3) Lost Labyrinth
    # 4) S.C.O.U.R.G.E.
    # 5) Stone-Soupe
    DUNGEON=""
  #}}}
  #EMULATORS {{{
    # 1) BSNES
    # 2) Desmume
    # 3) Dolphin
    # 4) ePSXe
    # 5) Project64
    # 6) Snes9x
    # 7) VisualBoyAdvanced
    # 8) wxMupen64Plus
    # 9) ZSNES
    EMULATORS=""
  #}}}
  #FPS {{{
    # 1) AlienArena
    # 2) Warsow
    # 3) Wolfenstein: Enemy Territory
    # 4) World of Padman
    # 5) Xonotic
    FPS=""
  #}}}
  #MMO {{{
    # 1) Heroes of Newerth
    # 2) League of Legends
    # 3) ManaPlus
    # 4) Runescape
    # 5) Savage II
    # 6) Spiral Knights
    # 7) Wakfu
    MMO=""
  #}}}
  #PUZZLE {{{
    # 1) Frozen Bubble
    # 2) Puzzle Moppet
    # 3) Numptyphysics
    PUZZLE=""
  #}}}
  #RPG {{{
    # 1) Ardentryst
    # 2) Flare
    # 3) Freedroid RPG
    RPG=""
  #}}}
  #RACING {{{
    # 1) Maniadrive
    # 2) Death Rally
    # 3) Stuntrally
    # 4) SupertuxKart
    # 5) Speed Dreams
    RACING=""
  #}}}
  #SIMULATION {{{
    # 1) Simultrans
    # 2) Theme Hospital
    # 3) OpenTTD
    SIMULATION=""
  #}}}
  #STRATEGY {{{
    # 1) 0ad
    # 2) Hedgewars
    # 3) MegaGlest
    # 4) Warzone 2100
    # 5) Wesnoth
    # 6) Zod
    STRATEGY=""
  #}}}
#}}}
#WEBSERVER {{{
  # 1) LAMP - APACHE, MariaDB & PHP + ADMINER
  # 2) LAPP - APACHE, POSTGRESQL & PHP + ADMINER
  # 3) LNMP - NGINX, MariaDB & PHP + ADMINER
  # 4) LNPP - NGINX, POSTGRESQL & PHP + ADMINER
  WEBSERVER=2
#}}}
#FONTS {{{
  # 1) ttf-anka-coder
  # 2) ttf-dejavu
  # 3) ttf-exljbris
  # 4) ttf-funfonts
  # 5) ttf-google-webfonts
  # 6) ttf-liberation
  # 7) ttf-ms-fonts
  # 8) ttf-vista-fonts
  # 9) wqy-microhei
  FONTS_OPTIONS="1-9"
#}}}
#EXTRA {{{
  # 1) Elementary Project
  EXTRA_OPTIONS=""
  #ELEMENTARY PROJECT {{{
    # 1) Audience
    # 2) Cerbere
    # 3) Contractor
    # 4) Eidete
    # 5) Dexter
    # 6) Feedler
    # 7) Files
    # 8) Footnote
    # 9) Foto
    #10) Gala
    #11) Geary
    #12) Lingo
    #13) Maya
    #14) Midori
    #15) Noise
    #16) Scratch
    #17) Plank
    #18) Pantheon Terminal
    #19) Slingshot
    #20) Snap
    #21) Switchboard
    #22) Wingpanel
    #23) eICONS
    #24) eGTK
    ELEMENTARY_OPTIONS=""
  #}}}
#}}}
