#!/bin/bash
#-------------------------------------------------------------------------------
#Created by helmuthdu mailto: helmuthdu[at]gmail[dot]com
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

#MAINMENU {{{
    # 1) Basic Setup
    # 2) Desktop Environment
    # 3) Accessories Apps
    # 4) Development Apps
    # 5) Office Apps
    # 6) System Apps
    # 7) Graphics Apps
    # 8) Internet Apps
    # 9) Audio Apps
    #10) Video Apps
    #11) Games
    #12) LAMP
    #13) Fonts
    #14) Fonts Configuration
    #15) Clean Orphan Packages
    MAINMENU="1-10 13"
#}}}
#BASIC SETUP{{{
    LANGSELECT="y"
    REFLECTOR="n"
    PACKAGESIGN="n"
    CUPS="y"
    GITTOR="y"
    NFS="n"
    SAMBA="y"
    SSH="y"
    TLP="n"
    CUSTOMREPO="n"
    #VIDEOCARD {{{
        # 1) Intel
        # 2) ATI
        # 3) nVidia
        # 4) Nouveau
        # 5) Virtualbox
        # 6) Vesa
        VIDEOCARD=3
    #}}}
    #ADDITIONAL FIRMWARE {{{
        FIRMWARE="n"
        # 1) alsa-firmware
        # 2) ipw2100
        # 3) ipw2200
        # 4) b43
        # 5) b43legacy
        # 6) broadcom-wl
        # 7) bluez-firmware
        # 8) libffado [Fireware Audio Devices]
        # 8) libraw1394 [IEE1394 Driver]
        # 9) sane-gt68xx-firmware
        FIRMWARE_OPTIONS=""
    #}}}
#}}}
#DESKTOP ENVIRONMENT {{{
    # 1) Cinnamon
    # 2) E17
    # 3) GNOME
    # 4) KDE
    # 5) LXDE
    # 6) OpenBox
    # 7) XFCE
    DESKTOPENV=3
    #CINNAMON {{{
        # 1) Cinnamon Applets
        # 2) Cinnamon Themes
        # 3) GNOME Icons
        # 4) GNOME Themes
        # 5) GNOME Packagekit
        # 6) Activity Journal
        # 7) Gloobus Preview
        CINNAMON_OPTIONS="1-5"
    #}}}
    #E17 {{{
        # 1) E17 Icons
        # 2) E17 Themes
        # 3) Elsa
        # 4) Icons
        # 5) Geeqie
        # 6) Gmrun
        # 7) PCManFM
        # 8) rxvt-unicode
        # 9) Scrot
        #10) Themes
        #11) Thunar
        #12) Xfburn
        E17_OPTIONS=""
    #}}}
    #GNOME {{{
        # 1) GNOME Icons
        # 2) GNOME Themes
        # 3) GNOME Shell
        # 4) GNOME Shell
        # 5) Packagekit
        # 6) Activity Journal
        # 7) Activity Log Manager
        # 8) Gloobus Preview
        GNOME_OPTIONS="1-5 7"
        #GNOME EXTENSIONS {{{
            # 1) gpaste
            # 2) gtile
            # 3) media-player
            # 4) noa11y
            # 5) pomodoro
            # 6) system-monitor
            # 7) user-theme
            # 8) weather
            GNOME_EXTENSIONS="1-8"
        #}}}
        #GNOME SHELL THEMES {{{
            # 1) Dark Shine
            # 2) Elegance
            # 3) Frieze
            GNOME_SHELL_THEMES="1-3"
        #}}}
    #}}}
    #KDE {{{
        # 1) Apper
        # 2) Bangarang
        # 3) Choqok
        # 4) Digikam
        # 5) K3b
        # 6) Rosa Icon
        # 7) Plasma Themes [Caledonia, Produkt, Ronak]
        # 8) Yakuake
        KDE_OPTIONS="1-8"
    #}}}
    #LXDE {{{
        # 1) Icons
        # 2) LXDM
        # 3) Xfburn
        LXDE_OPTIONS=""
    #}}}
    #OPENBOX {{{
        # 1) Xcompmgr
        # 2) Icons
        # 3) Geeqie
        # 4) Gmrun
        # 5) PCManFM
        # 6) rxvt-unicode
        # 7) Scrot
        # 8) Slim
        # 9) GTK Themes
        #10) Thunar
        #11) Tint2
        #12) Volwheel
        #13) Xfburn
        OPENBOX_OPTIONS=""
    #}}}
    #XFCE {{{
        # 1) Icons
        # 2) Themes
        # 3) Slim
        XFCE_OPTIONS="1-3"
    #}}}
    #E17/GNOME/LXDE/OPENBOX/XFCE ICONS {{{
        # 1) Awoken
        # 2) Faenza
        # 3) Faenza-Cupertino
        # 4) Faience
        # 5) Elementary
        GNOME_ICONS="2-5"
    #}}}
    #GTK2/GTK3 THEMES {{{
        # 1) Adwaita Cupertino
        # 2) Bluebird
        # 3) eGTK
        # 4) Greybird
        # 5) Light (Aka Ambiance/Radiance)
        # 6) Orion
        # 7) Zukini
        # 8) Zukitwo
        GTK_THEMES="2-8"
    #}}}
    #NETWORKMANAGER #{{{
        # 1) Networkmanager
        # 2) Wicd
        # 3) None
        NETWORKMANAGER=1
    #}}}
#}}}
#ACCESSORIES {{{
    # 1) Cairo Dock
    # 2) Conky + CONKY-colors
    # 3) Deepin Scrot
    # 4) Dockbarx
    # 5) Docky
    # 6) Galculator/Speedcrunch
    # 7) Gnome-Pie
    # 8) Guake
    # 9) Kupfer
    #10) Pyrenamer
    #11) Shutter
    #12) Synapse
    #13) Terminator
    #14) Zim
    ACCESSORIES_OPTIONS="2 13"
#}}}
#DEVELOPEMENT {{{
    # 1) Aptana Studio
    # 2) Bluefish
    # 3) Eclipse
    # 4) Emacs
    # 5) Gvim
    # 6) Geany
    # 7) IntelliJ IDEA
    # 8) Netbeans
    # 9) Oracle Java
    #10) QT Creator
    #11) Sublime Text 2
    #12) Debugger Tools [Valgrind, Gdb, Splint, Tidyhtml, Pyflakes, Jsl]
    #13) MySQL Workbench
    #14) Meld
    #15) RabbitVCS
    DEVELOPMENT_OPTIONS="9 5 12"
    #ECLIPSE {{{
        # 1) Eclipse Classic
        # 2) Eclipse IDE for C/C++ Developers
        # 3) Android Development Tools for Eclipse
        # 4) Web Development Tools for Eclipse
        # 5) PHP Development Tools for Eclipse
        # 6) Python Development Tools for Eclipse
        # 7) Aptana Studio plugin for Eclipse
        # 8) Vim-like editing plugin for Eclipse
        # 9) Git support plugin for Eclipse
        ECLIPSE_OPTIONS="1"
    #}}}
#}}}
#OFFICE {{{
    # 1) LibreOffice
    # 2) GNOME Office [Abiword, Gnumeric]
    # 3) Latex + Texmaker
    # 4) CHM Viewer
    # 5) GCStar
    # 6) Homebank
    # 7) Impressive
    # 8) Nitrotask
    # 9) OCRFeeder
    #10) Xmind
    #11) Zathura
    OFFICE_OPTIONS="1 3 6-8 11"
#}}}
#SYSTEM TOOLS {{{
    # 1) Gparted
    # 2) Grsync
    # 3) Htop
    # 4) Virtualbox
    # 5) Wine
    SYSTEMTOOLS_OPTIONS="2 3 5"
#}}}
#GRAPHICS {{{
    # 1) Blender
    # 2) Gimp
    # 3) Gimp-plugins
    # 4) Gthumb
    # 5) Inkscape
    # 6) MComix
    # 7) Mypaint
    # 8) Scribus
    # 9) Shotwell
    GRAPHICS_OPTIONS="2-7 9"
#}}}
#INTERNET {{{
    # 1) Dropbox
    # 2) Chromium
    # 3) Google Earth
    # 4) Google Chrome
    # 5) Jdownloader
    # 6) Irssi
    # 7) Midori
    # 8) Mozilla Firefox
    # 9) Mozilla Thunderbird
    #10) Pidgin
    #11) Remmina
    #12) Skype
    #13) Steadyflow
    #14) Teamspeak
    #15) Teamviewer
    #16) Trasmission
    #17) X-Chat/Konversation
    INTERNET_OPTIONS="1 3 4 5 8"
#}}}
#LAMP {{{
    LAMP="y"
#}}}
#AUDIO {{{
    # 1) Amarok
    # 2) Audacious
    # 3) Banshee
    # 4) Clementine
    # 5) Deadbeef
    # 6) Exaile
    # 7) Musique
    # 8) Nuvola
    # 9) Rhythmbox
    #10) Radiotray
    #11) Spotify
    #12) Soundconverter
    #13) Puddletag
    #14) Audacity
    #15) MIDI
    #16) Codecs
    AUDIO_OPTIONS="4 12 16"
#}}}
#VIDEO {{{
    # 1) Audience
    # 2) Gnome Mplayer
    # 3) Parole
    # 4) Minitube
    # 5) Miro
    # 6) Rosa Media Player
    # 7) SMplayer
    # 8) VLC
    # 9) XBMC
    #10) Arista
    #11) Transmageddon
    #12) Kdenlive
    #13) Openshot
    #14) Pitivi
    #15) Kazam
    #16) Codecs
    VIDEO_OPTIONS="8 9 16"
#}}}
#GAMES {{{
    # 1) Action/Adventure
    # 2) Arcade/Platformer
    # 3) Dungeon
    # 4) Emulators
    # 5) FPS
    # 6) MMO
    # 7) Puzzle
    # 8) RPG
    # 9) Racing
    #10) Simulation
    #11) Strategy
    GAMES_OPTIONS="1-11"
    #ACTION {{{
        # 1) Astromenace
        # 2) Counter-Strike 2D
        # 3) Dead Cyborg
        # 4) M.A.R.S.
        # 5) OpenTyrian
        # 6) Sonic Robot Bast 2
        # 7) SteelStorm
        # 8) Yo Frankie!
        ACTION=""
    #}}}
    #ARCADE {{{
        # 1) Abuse
        # 2) Battle Tanks
        # 3) Bomberclone
        # 4) Those Funny Funguloids
        # 5) Frogatto
        # 6) Goonies
        # 7) Mari0
        # 8) Neverball
        # 9) Opensonic
        #10) Robombs
        #11) Super Mario Chronicles
        #12) X-Moto
        ARCADE=""
    #}}}
    #DUNGEON {{{
        # 1) Adom
        # 2) Tales of MajEyal
        # 3) Lost Labyrinth
        # 4) S.C.O.U.R.G.E.
        DUNGEON=""
    #}}}
    #EMULATORS {{{
        # 1) BSNES
        # 2) Desmume
        # 3) Dolphin
        # 4) ePSXe
        # 5) Project64
        # 6) VisualBoyAdvanced
        # 7) wxMupen64Plus
        # 8) ZSNES
        EMULATORS=""
    #}}}
    #FPS {{{
        # 1) AlienArena
        # 2) Warsow
        # 3) Wolfenstein: Enemy Territory
        # 4) World of Padman
        # 5) Xonotic
        FPS=""
    #}}}
    #MMO {{{
        # 1) ManaPlus
        # 2) Heroes of Newerth
        # 3) Savage II
        # 4) Spiral Knights
        # 5) Wakfu
        MMO=""
    #}}}
    #PUZZLE {{{
        # 1) Frozen Bubble
        # 2) Numptyphysics
        PUZZLE=""
    #}}}
    #RPG {{{
        # 1) Ardentryst
        # 2) Flare
        # 3) Freedroid RPG
        RPG=""
    #}}}
    #RACING {{{
        # 1) Maniadrive
        # 2) Death Rally
        # 3) Stuntrally
        # 4) SupertuxKart
        # 5) Speed Dreams
        RACING=""
    #}}}
    #SIMULATION {{{
        # 1) Simultrans
        # 2) Theme Hospital
        # 3) OpenTTD
        SIMULATION=""
    #}}}
    #STRATEGY {{{
        # 1) 0ad
        # 2) Hedgewars
        # 3) MegaGlest
        # 4) Warzone 2100
        # 5) Wesnoth
        # 6) Zod
        STRATEGY=""
    #}}}
#}}}
#FONTS {{{
    # 1) ttf-dejavu
    # 2) ttf-google-webfonts
    # 3) ttf-funfonts
    # 4) ttf-kochi-substitute
    # 5) ttf-liberation
    # 6) ttf-mac-fonts
    # 7) ttf-ms-fonts
    # 8) ttf-vista-fonts
    FONTS_OPTIONS="1 2 4-8"
    GOOGLE_FONTS="y"
#}}}
#FONTS CONFIGURATION {{{
    # 1) Ubuntu patched packages
    # 2) Cleartype patched packages
    # 3) Infinality patched packages
    # 4) Reverting to unpatched packages
    FONTSCONFIG_OPTION=""
#}}}
