#!/bin/bash
#-------------------------------------------------------------------------------
#Created by helmuthdu mailto: helmuthdu[at]gmail[dot]com
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

#MAINMENU {{{
    # 1) Basic Setup
    # 2) Desktop Environment
    # 3) Accessories Apps
    # 4) Development Apps
    # 5) Office Apps
    # 6) System Apps
    # 7) Graphics Apps
    # 8) Internet Apps
    # 9) Audio Apps
    #10) Video Apps
    #11) Games
    #12) LAMP
    #13) Fonts
    #14) Extra
    #15) Clean Orphan Packages
    MAINMENU="1-13 15"
#}}}
#BASIC SETUP{{{
    FIRMWARE="n"
    CUPS="y"
    CUSTOMREPO="n"
    GITTOR="y"
    LANGSELECT="y"
    NFS="n"
    PRELOAD="y"
    ZRAM="y"
    REFLECTOR="n"
    SAMBA="y"
    SSH="y"
    TLP="n"
    #VIDEOCARD {{{
        # 1) Intel
        # 2) ATI
        # 3) nVidia
        # 4) Nouveau
        # 5) Virtualbox
        # 6) Vesa
        VIDEOCARD=3
    #}}}
    #ADDITIONAL FIRMWARE {{{
        # 1) alsa-firmware
        # 2) ipw2100
        # 3) ipw2200
        # 4) b43
        # 5) b43legacy
        # 6) broadcom-wl
        # 7) zd1211-firmware
        # 8) bluez-firmware
        # 9) libffado [Fireware Audio Devices]
        #10) libraw1394 [IEE1394 Driver]
        #11) sane-gt68xx-firmware
        FIRMWARE_OPTIONS=""
    #}}}
#}}}
#DESKTOP ENVIRONMENT {{{
    # 1) Awesome
    # 2) Cinnamon
    # 3) E17
    # 4) GNOME
    # 5) KDE
    # 6) LXDE
    # 7) OpenBox
    # 8) XFCE
    # 9) Unity (Experimental)
    DESKTOPENV=4
    #AWESOME/OPENBOX {{{
        # 1) Xcompmgr
        # 2) Icons
        # 3) Viewnior
        # 4) Gmrun
        # 5) PCManFM
        # 6) rxvt-unicode
        # 7) Scrot
        # 8) Display Manager
        # 9) GTK Themes
        #10) Thunar
        #11) Tint2
        #12) Volwheel
        #13) Xfburn
        AWESOMEOB_OPTIONS=""
    #}}}
    #CINNAMON {{{
        # 1) Cinnamon Applets
        # 2) Cinnamon Themes
        # 3) GNOME Icons
        # 4) GNOME Themes
        # 5) GNOME Packagekit
        # 6) Activity Journal
        # 7) Gloobus Preview
        CINNAMON_OPTIONS="1-5"
    #}}}
    #E17 {{{
        # 1) E17 Icons
        # 2) E17 Themes
        # 3) Display Manager
        # 4) Icons
        # 5) Viewnior
        # 6) Gmrun
        # 7) PCManFM
        # 8) rxvt-unicode
        # 9) Scrot
        #10) GTK Themes
        #11) Thunar
        #12) Xfburn
        E17_OPTIONS=""
    #}}}
    #GNOME {{{
        # 1) GNOME Icons
        # 2) GNOME Themes
        # 3) GNOME Shell
        # 4) GNOME Shell
        # 5) Packagekit
        # 6) Activity Journal
        # 7) Activity Log Manager
        # 8) Gloobus Preview
        GNOME_OPTIONS="1-5"
        #GNOME EXTENSIONS {{{
            # 1) disper
            # 2) gpaste
            # 3) gtile
            # 4) media-player
            # 5) noa11y
            # 6) pomodoro
            # 7) system-monitor
            # 8) user-theme
            # 9) weather
            GNOME_EXTENSIONS="1-9"
        #}}}
        #GNOME SHELL THEMES {{{
            # 1) Default Mod
            # 2) Dark Shine
            # 3) Elegance
            # 4) eOS
            # 5) Frieze
            # 6) Google+
            GNOME_SHELL_THEMES="1-6"
        #}}}
    #}}}
    #KDE {{{
        # 1) Apper
        # 2) Bangarang
        # 3) Choqok
        # 4) Digikam
        # 5) K3b
        # 6) Rosa Icon
        # 7) Plasma Themes [Caledonia, Produkt, Ronak]
        # 8) Yakuake
        KDE_OPTIONS="1-8"
    #}}}
    #LXDE {{{
        # 1) Icons
        # 2) Display Manager
        # 3) GTK Themes
        # 4) Viewnior
        # 5) Xfburn
        LXDE_OPTIONS=""
    #}}}
    #XFCE {{{
        # 1) Icons
        # 2) GTK Themes
        # 3) Display Manager
        XFCE_OPTIONS="1-3"
    #}}}
    #ICONS {{{
        # 1) Awoken
        # 2) Faenza
        # 3) Faenza-Cupertino
        # 4) Faience
        # 5) Elementary
        GNOME_ICONS="2-4"
    #}}}
    #GTK THEMES {{{
        # 1) Adwaita Cupertino
        # 2) Boomerang
        # 3) Blackbird
        # 4) Bluebird
        # 5) eGTK
        # 6) Greybird
        # 7) Light (Aka Ambiance/Radiance)
        # 8) Orion
        # 9) Zukini
        #10) Zukitwo
        GTK_THEMES="2-10"
    #}}}
    #DISPLAY MANAGER {{{
        # 1) Elsa
        # 2) GDM
        # 3) LightDM
        # 4) LXDM
        # 5) Slim
        DISPLAY_MANAGER="4"
    #}}}
    #NETWORK MANAGER {{{
        # 1) NetworkManager
        # 2) Wicd
        # n) None
        NETWORKMANAGER="1"
    #}}}
#}}}
#ACCESSORIES {{{
    # 1) Cairo Dock
    # 2) Conky + CONKY-colors
    # 3) Deepin Scrot
    # 4) Dockbarx
    # 5) Docky
    # 6) Galculator/Speedcrunch
    # 7) Gnome-Pie
    # 8) Guake
    # 9) Kupfer
    #10) Pyrenamer
    #11) Shutter
    #12) Synapse
    #13) Terminator
    #14) Zim
    ACCESSORIES_OPTIONS=""
#}}}
#DEVELOPEMENT {{{
    # 1) Aptana Studio
    # 2) Bluefish
    # 3) Eclipse
    # 4) Emacs
    # 5) Gvim
    # 6) Geany
    # 7) IntelliJ IDEA
    # 8) Kdevelop
    # 9) Netbeans
    #10) Oracle Java
    #11) QT Creator
    #12) Sublime Text 2
    #13) Debugger Tools [Valgrind, Gdb, Splint, Tidyhtml, Pyflakes, Jsl]
    #14) MySQL Workbench
    #15) Meld
    #16) RabbitVCS
    DEVELOPMENT_OPTIONS="10 5 13"
    #ECLIPSE {{{
        # 1) Eclipse Classic
        # 2) Eclipse IDE for C/C++ Developers
        # 3) Android Development Tools for Eclipse
        # 4) Web Development Tools for Eclipse
        # 5) PHP Development Tools for Eclipse
        # 6) Python Development Tools for Eclipse
        # 7) Aptana Studio plugin for Eclipse
        # 8) Vim-like editing plugin for Eclipse
        # 9) Git support plugin for Eclipse
        ECLIPSE_OPTIONS="1"
    #}}}
#}}}
#OFFICE {{{
    # 1) LibreOffice
    # 2) Abiword+Gnumeric|Calligra
    # 3) Latex + Texmaker
    # 4) Calibre
    # 5) GCStar
    # 6) Homebank
    # 7) Impressive
    # 8) Nitrotask
    # 9) OCRFeeder
    #10) Xmind
    #11) Zathura
    OFFICE_OPTIONS="1 6 8 10"
#}}}
#SYSTEM TOOLS {{{
    # 1) Gparted
    # 2) Grsync
    # 3) Htop
    # 4) Virtualbox
    # 5) Webmin
    # 6) Wine
    SYSTEMTOOLS_OPTIONS="1-3 6"
#}}}
#GRAPHICS {{{
    # 1) Blender
    # 2) Gimp
    # 3) Gimp-plugins
    # 4) Gthumb
    # 5) Inkscape
    # 6) MComix
    # 7) Mypaint
    # 8) Scribus
    # 9) Shotwell
    #10) XnViewMP
    GRAPHICS_OPTIONS="2-7 9"
#}}}
#INTERNET {{{
    # 1) Browser
    # 2) Download|Fileshare
    # 3) Email|RSS
    # 4) Instant Messaging
    # 5) IRC
    # 6) Mapping Tools
    # 7) VNC|Desktop Share
    INTERNET_OPTIONS="1-7"
    #BROWSER {{{
        # 1) Chromium
        # 2) Google Chrome
        # 3) Midori|Rekonq
        # 4) Mozilla Firefox
        # 5) Opera
        BROWSERS_OPTIONS="2 4"
    #}}}
    #DOWNLOAD|FILESHARE {{{
        # 1) Deluge
        # 2) Dropbox
        # 3) Jdownloader
        # 4) Nitroshare
        # 5) Sparkleshare
        # 6) Steadyflow
        # 7) Trasmission
        DOWNLOAD_OPTIONS="2 3"
    #}}}
    #EMAIL|RSS {{{
        # 1) Mozilla Thunderbird
        # 2) Liferea
        # 3) LightRead
        EMAIL_OPTIONS="3"
    #}}}
    #IM {{{
        # 1) Emesene
        # 2) Google Talk-Plugin
        # 3) Pidgin
        # 4) Skype
        # 5) Teamspeak
        IM_OPTIONS="4"
    #}}}
    #IRC {{{
        # 1) Irssi
        # 2) X-Chat|Quassel
        IRC_OPTIONS=""
    #}}}
    #MAPPING {{{
        # 1) Google Earth
        # 2) NASA World Wind
        MAPPING_OPTIONS="1"
    #}}}
    #VNC|Desktop Share {{{
        # 1) Remmina
        # 2) Teamviewer
        VNC_OPTIONS=""
    #}}}
#}}}
#WEBSERVER {{{
    # 1) LAMP - APACHE, MYSQL & PHP + ADMINER
    # 2) LAPP - APACHE, POSTGRESQL & PHP + ADMINER
    LAMP="2"
#}}}
#AUDIO {{{
    # 1) Amarok
    # 2) Audacious
    # 3) Banshee
    # 4) Clementine
    # 5) Deadbeef
    # 6) Musique
    # 7) Nuvola
    # 8) Rhythmbox
    # 9) Radiotray
    #10) Spotify
    #11) Tomahawk
    #12) Soundconverter|Soundkonverter
    #13) Puddletag
    #14) Audacity
    #15) OcenAudio
    #16) MIDI
    #17) Codecs
    AUDIO_OPTIONS="4 12 17"
#}}}
#VIDEO {{{
    # 1) Audience
    # 2) Gnome Mplayer
    # 3) Parole
    # 4) Minitube
    # 5) Miro
    # 6) Rosa Media Player
    # 7) SMplayer
    # 8) VLC
    # 9) XBMC
    #10) Arista
    #11) Transmageddon
    #12) Openshot
    #13) Pitivi|Kdenlive
    #14) Kazam
    #15) Codecs
    VIDEO_OPTIONS="8 9 15"
#}}}
#GAMES {{{
    # 1) Action|Adventure
    # 2) Arcade|Platformer
    # 3) Dungeon
    # 4) Emulators
    # 5) FPS
    # 6) MMO
    # 7) Puzzle
    # 8) RPG
    # 9) Racing
    #10) Simulation
    #11) Strategy
    GAMES_OPTIONS="1-11"
    #ACTION {{{
        # 1) Astromenace
        # 2) Counter-Strike 2D
        # 3) Dead Cyborg
        # 4) M.A.R.S.
        # 5) Nikki
        # 6) OpenTyrian
        # 7) Sonic Robot Bast 2
        # 8) SteelStorm
        # 9) Yo Frankie!
        ACTION=""
    #}}}
    #ARCADE {{{
        # 1) Abuse
        # 2) Battle Tanks
        # 3) Bomberclone
        # 4) Those Funny Funguloids
        # 5) Frogatto
        # 6) Goonies
        # 7) Mari0
        # 8) Neverball
        # 9) Opensonic
        #10) Robombs
        #11) Super Mario Chronicles
        #12) X-Moto
        ARCADE=""
    #}}}
    #DUNGEON {{{
        # 1) Adom
        # 2) Tales of MajEyal
        # 3) Lost Labyrinth
        # 4) S.C.O.U.R.G.E.
        DUNGEON=""
    #}}}
    #EMULATORS {{{
        # 1) BSNES
        # 2) Desmume
        # 3) Dolphin
        # 4) ePSXe
        # 5) Project64
        # 6) VisualBoyAdvanced
        # 7) wxMupen64Plus
        # 8) ZSNES
        EMULATORS=""
    #}}}
    #FPS {{{
        # 1) AlienArena
        # 2) Warsow
        # 3) Wolfenstein: Enemy Territory
        # 4) World of Padman
        # 5) Xonotic
        FPS=""
    #}}}
    #MMO {{{
        # 1) ManaPlus
        # 2) Heroes of Newerth
        # 3) Runescape
        # 4) Savage II
        # 5) Spiral Knights
        # 6) Wakfu
        MMO=""
    #}}}
    #PUZZLE {{{
        # 1) Frozen Bubble
        # 2) Numptyphysics
        PUZZLE=""
    #}}}
    #RPG {{{
        # 1) Ardentryst
        # 2) Flare
        # 3) Freedroid RPG
        RPG=""
    #}}}
    #RACING {{{
        # 1) Maniadrive
        # 2) Death Rally
        # 3) Stuntrally
        # 4) SupertuxKart
        # 5) Speed Dreams
        RACING=""
    #}}}
    #SIMULATION {{{
        # 1) Simultrans
        # 2) Theme Hospital
        # 3) OpenTTD
        SIMULATION=""
    #}}}
    #STRATEGY {{{
        # 1) 0ad
        # 2) Hedgewars
        # 3) MegaGlest
        # 4) Warzone 2100
        # 5) Wesnoth
        # 6) Zod
        STRATEGY=""
    #}}}
#}}}
#FONTS {{{
    # 1) ttf-dejavu
    # 2) ttf-google-webfonts
    # 3) ttf-funfonts
    # 4) ttf-kochi-substitute
    # 5) ttf-liberation
    # 6) ttf-mac-fonts
    # 7) ttf-ms-fonts
    # 8) ttf-vista-fonts
    # 9) ttf-wgy-microhei
    FONTS_OPTIONS="1 3-9"
    GOOGLE_FONTS="y"
#}}}
#EXTRA {{{
    # 1) Elementary Project
    EXTRA_OPTIONS=""
    #ELEMENTARY PROJECT {{{
        # 1) Audience
        # 2) Contractor
        # 3) Eidete
        # 4) Dexter
        # 5) Feedler
        # 6) Files
        # 7) Footnote
        # 8) Gala
        # 9) Geary
        #10) Lingo
        #11) Maya
        #12) Midori
        #13) Noise
        #14) Scratch
        #15) Plank
        #16) Pantheon Terminal
        #17) Slingshot
        #18) Switchboard
        #19) Wingpanel
        #20) eICONS
        #21) eGTK
        ELEMENTARY_OPTIONS="1-20"
    #}}}
#}}}
